#!/bin/sh

PROG="httpd"
PROG_WEB="website"
PROG_PATH="/data/app/$PROG"
PROG_PATH_WEB="/data/app/$PROG_WEB"
MSG_PREFIX=" *"
echo "$MSG_PREFIX start install $PROG"

if [ -d "$PROG_APTH" ]
then
        rm -rf $PROG_APTH
		rm -rf $PROG_PATH_WEB
fi

mkdir -p $PROG_PATH
mkdir -p $PROG_PATH_WEB

cp -v -n -r ./$PROG/* $PROG_PATH/
cp -v -n -r ./$PROG_WEB/* $PROG_PATH_WEB/

ln  -f -s $PROG_PATH/$PROG /etc/init.d/$PROG

if [ -x "/usr/bin/node" ]
then
	echo "$MSG_PREFIX install nodejs"
else
	echo "$MSG_PREFIX not install nodejs"
	exit 1
fi

update-rc.d  $PROG defaults 50

echo "$MSG_PREFIX install sucess $PROG"

service $PROG start


