#!/bin/sh

PROG="httpd"
PROG_WEB="website"
PROG_PATH="/data/app/$PROG"
PROG_PATH_WEB="/data/app/$PROG_WEB"
PROG_LOG_PATH="/var/log/$PROG"
MSG_PREFIX=" *"
echo "$MSG_PREFIX start install $PROG"

##check mysql is installed
echo "\n * check install mysql-server"
mysql_server=`dpkg -l | awk '{print $2}' | grep '^mysql-server' | head -n 1 | wc -L`
if [ $mysql_server -gt 0 ] ; then
	echo " * installed mysql-server" 
	echo " * if vistor fail please"
	echo " * login mysql (mysql -u root -p)"
	echo " * create database fcloud"
	echo " * use fcloud"
	echo " * source $PWD/httpd/fcloud.dbtxt"
	echo " * execute up command"
else
	echo " * please install mysql_server"
	exit 1
fi

service httpd stop

if [ -d "$PROG_LOG_PATH" ] ; then
	echo "$MSG_PREFIX $PROG_LOG_PATH exits"
else 
	mkdir -p $PROG_LOG_PATH
	chmod 777 $PROG_LOG_PATH
fi

if [ -d "$PROG_PATH" ] ; then
        rm -rf $PROG_PATH
		rm -rf $PROG_PATH_WEB
fi

mkdir -p $PROG_PATH
mkdir -p $PROG_PATH_WEB

cp -v -n -r ./$PROG/* $PROG_PATH/
cp -v -n -r ./$PROG_WEB/* $PROG_PATH_WEB/

if [ -f "/etc/init.d/$PROG" ] ; then
	echo "$MSG_PREFIX /etc/init.d/$PROG  already exist delete"
	rm -f /etc/init.d/$PROG
fi

echo "#/bin/sh"  >> /etc/init.d/$PROG
echo "ARGS=\$*" >> /etc/init.d/$PROG
echo "echo \"su -c '$PROG_PATH/$PROG \$ARGS' linaro\" | sh" >> /etc/init.d/$PROG
chmod 755 /etc/init.d/$PROG

if [ -x "/usr/bin/node" ] ; then
	echo "$MSG_PREFIX install nodejs"
else
	echo "$MSG_PREFIX not install nodejs"
	exit 1
fi

if [ -f "/etc/rc0.d/K50httpd" ] ; then
	echo "$MSG_PREFIX not need add start for boot"
else
	echo "$MSG_PREFIX add start for boot"
	update-rc.d  $PROG defaults 50
fi


echo "$MSG_PREFIX install sucess $PROG"

service $PROG start

echo "$MSG_PREFIX if service not started please run httpd/npm_list add module depends"


