#!/bin/sh
### BEGIN INIT INFO
#
# Provides:	 httpd.js
# Required-Start:	$local_fs  $remote_fs
# Required-Stop:	$local_fs  $remote_fs
# Default-Start: 	2 3 4 5
# Default-Stop: 	0 1 6
# Short-Description:	initscript
# Description: 	This file should be used to construct scripts to be placed in /etc/init.d.
#
### END INIT INFO

## Fill in name of program here.
PROG="httpd.js"
PROG_PATH="/usr/bin/nodejs /data/app/httpd" #::# Not need, but sometimes helpful (if $PROG resides in /opt for example).
MSG_PREFIX=" *"
FM_ARGS="/mnt/sda2/f"
PH_ARGS="/mnt/sda2/f/photos  /mnt/sda2/f/thum"
PID_PATH="/var/run/"
STD_OUT="/dev/null"

start_fm(){

    pid=`ps -ef|grep httpd.js |grep fm |awk '{print $2}' | head -n 1`
    if [ -z "$pid" ]; then
        $PROG_PATH/$PROG fm $FM_ARGS >$STD_OUT 2>&1 &
        pid=`ps -ef|grep httpd.js |grep fm |awk '{print $2}' | head -n 1`
        echo "$MSG_PREFIX $PROG fm started"
    else
        echo "$MSG_PREFIX $PROG fm is currently running..."
    fi

}

stop_fm(){

    pid=`ps -ef|grep httpd.js |grep fm |awk '{print $2}' | head -n 1`
    if [ -n "$pid" ]; then
        kill -9 $pid
        echo "$MSG_PREFIX $PROG fm stopped"
    else
        echo "$MSG_PREFIX $PROG.fm not started!" 
    fi

}

start_arduino(){

    pid=`ps -ef|grep httpd.js |grep arduino |awk '{print $2}' | head -n 1`
    if [ -z "$pid" ]; then
        $PROG_PATH/$PROG arduino >$STD_OUT 2>&1 &
        pid=`ps -ef|grep httpd.js |grep arduino |awk '{print $2}' | head -n 1`
        echo "$MSG_PREFIX $PROG arduino started"
    else
        echo "$MSG_PREFIX $PROG arduino is currently running..."
    fi

}

stop_arduino(){

    pid=`ps -ef|grep httpd.js |grep arduino |awk '{print $2}' | head -n 1`
    if [ -n "$pid" ]; then
        kill -9 $pid
        echo "$MSG_PREFIX $PROG arduino stopped"
    else
        echo "$MSG_PREFIX $PROG.arduino not started!"
    fi

}

start_baidupansync(){

    pid=`ps -ef|grep httpd.js |grep baidupansync |awk '{print $2}' | head -n 1`
    if [ -z "$pid" ]; then
        $PROG_PATH/$PROG baidupansync >$STD_OUT 2>&1 &
        pid=`ps -ef|grep httpd.js |grep baidupansync |awk '{print $2}' | head -n 1`
        echo "$MSG_PREFIX $PROG baidupansync started"
    else
        echo "$MSG_PREFIX $PROG baidupansync is currently running..."
    fi

}

stop_baidupansync(){

    pid=`ps -ef|grep httpd.js |grep baidupansync |awk '{print $2}' | head -n 1`
    if [ -n "$pid" ]; then
        kill -9 $pid
        echo "$MSG_PREFIX $PROG baidupansync stopped"
    else
        echo "$MSG_PREFIX $PROG.baidupansync not started!" 
    fi

}

start_platform(){

    pid=`ps -ef|grep httpd.js |grep platform |awk '{print $2}' | head -n 1`
    if [ -z "$pid" ]; then
        $PROG_PATH/$PROG platform >$STD_OUT 2>&1 &
        pid=`ps -ef|grep httpd.js |grep platform |awk '{print $2}' | head -n 1`
        echo "$MSG_PREFIX $PROG platform started"
    else
        echo "$MSG_PREFIX $PROG platform is currently running..."
    fi

}

stop_platform(){

    pid=`ps -ef|grep httpd.js |grep platform |awk '{print $2}' | head -n 1`
    if [ -n "$pid" ]; then
        kill -9 $pid
        echo "$MSG_PREFIX $PROG platform stopped"
    else
        echo "$MSG_PREFIX $PROG.platform not started!"
    fi

}

start_photos(){

    pid=`ps -ef|grep httpd.js |grep photos |awk '{print $2}' | head -n 1`
    if [ -z "$pid" ]; then
        $PROG_PATH/$PROG photos $PH_ARGS >$STD_OUT 2>&1 &
        pid=`ps -ef|grep httpd.js |grep photos |awk '{print $2}' | head -n 1`
        echo "$MSG_PREFIX $PROG photos started"
    else
        echo "$MSG_PREFIX $PROG photos is currently running..."
    fi

}

stop_photos(){

    pid=`ps -ef|grep httpd.js |grep photos |awk '{print $2}' | head -n 1`
    if [ -n "$pid" ]; then
        kill -9 $pid
        echo "$MSG_PREFIX $PROG photos stopped"
    else
        echo "$MSG_PREFIX $PROG.photos not started!"
    fi

}

start() {
    echo "$MSG_PREFIX begin start $1"
    case "$1" in
        fm)
            start_fm
        ;;
        arduino)
            start_arduino
        ;;
        baidupansync)
            start_baidupansync
        ;;
        platform)
            start_platform
        ;;
        photos)
            start_photos
        ;;
        **)
            echo "$MSG_PREFIX start all"
            start_fm
            start_arduino
            start_baidupansync
            start_platform
            start_photos
        ;;
    esac

}

stop() {
    echo "$MSG_PREFIX begin stop $1"
    case "$1" in
        fm)
            stop_fm
        ;;
        arduino)
            stop_arduino
        ;;
        baidupansync)
            stop_baidupansync
        ;;
        platform)
            stop_platform
        ;;
         photos)
            stop_photos
        ;;
        **)
            echo "$MSG_PREFIX stop all"
            stop_fm
            stop_arduino
            stop_baidupansync
            stop_platform
            stop_photos
        ;;
    esac

}

## Check to see if we are running as root first.

if [ "$(id -u)" != "1000" ]; then
    echo "This script must be run as linro" 1>&2
    exit 1
fi


case "$1" in
    start)
        start $2
        exit 0
    ;;
    stop)
        stop $2
        exit 0
    ;;
    reload|restart|force-reload)
        stop $2
        start $2
        exit 0
    ;;
    **)
        echo "Usage: $0 { start | stop | reload } [ fm | arduino | baidupansync | platform | photos ]" 1>&2
        exit 1
    ;;
esac

